// Exchange configurations for all major world stock exchanges
export const EXCHANGES = {
  NASDAQ: {
    id: 'NASDAQ',
    name: 'NASDAQ',
    country: 'USA',
    flag: '🇺🇸',
    timezone: 'America/New_York',
    open: '09:30',
    close: '16:00',
    currency: 'USD',
    color: '#00b4d8',
    symbols: ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'NVDA', 'META', 'TSLA', 'NFLX', 'AMD', 'INTC', 'PYPL', 'ADBE'],
  },
  NYSE: {
    id: 'NYSE',
    name: 'New York Stock Exchange',
    country: 'USA',
    flag: '🇺🇸',
    timezone: 'America/New_York',
    open: '09:30',
    close: '16:00',
    currency: 'USD',
    color: '#0077b6',
    symbols: ['JPM', 'BAC', 'WMT', 'JNJ', 'XOM', 'CVX', 'PG', 'KO', 'DIS', 'GE', 'GS', 'MS'],
  },
  LSE: {
    id: 'LSE',
    name: 'London Stock Exchange',
    country: 'UK',
    flag: '🇬🇧',
    timezone: 'Europe/London',
    open: '08:00',
    close: '16:30',
    currency: 'GBP',
    color: '#c8102e',
    symbols: ['SHEL.L', 'HSBA.L', 'AZN.L', 'BP.L', 'GSK.L', 'RIO.L', 'ULVR.L', 'BATS.L'],
  },
  BSE: {
    id: 'BSE',
    name: 'Bombay Stock Exchange',
    country: 'India',
    flag: '🇮🇳',
    timezone: 'Asia/Kolkata',
    open: '09:15',
    close: '15:30',
    currency: 'INR',
    color: '#f77f00',
    symbols: ['RELIANCE.BO', 'TCS.BO', 'INFY.BO', 'HDFCBANK.BO', 'ICICIBANK.BO', 'HINDUNILVR.BO'],
  },
  NSE: {
    id: 'NSE',
    name: 'National Stock Exchange of India',
    country: 'India',
    flag: '🇮🇳',
    timezone: 'Asia/Kolkata',
    open: '09:15',
    close: '15:30',
    currency: 'INR',
    color: '#023e8a',
    symbols: ['NIFTY50', 'RELIANCE.NS', 'TCS.NS', 'INFY.NS', 'HDFCBANK.NS', 'WIPRO.NS'],
  },
  ASX: {
    id: 'ASX',
    name: 'Australian Securities Exchange',
    country: 'Australia',
    flag: '🇦🇺',
    timezone: 'Australia/Sydney',
    open: '10:00',
    close: '16:00',
    currency: 'AUD',
    color: '#ffb703',
    symbols: ['CBA.AX', 'BHP.AX', 'CSL.AX', 'NAB.AX', 'WBC.AX', 'ANZ.AX', 'MQG.AX'],
  },
  TSX: {
    id: 'TSX',
    name: 'Toronto Stock Exchange',
    country: 'Canada',
    flag: '🇨🇦',
    timezone: 'America/Toronto',
    open: '09:30',
    close: '16:00',
    currency: 'CAD',
    color: '#e63946',
    symbols: ['RY.TO', 'TD.TO', 'ENB.TO', 'CNR.TO', 'BMO.TO', 'SU.TO'],
  },
  HKEX: {
    id: 'HKEX',
    name: 'Hong Kong Stock Exchange',
    country: 'Hong Kong',
    flag: '🇭🇰',
    timezone: 'Asia/Hong_Kong',
    open: '09:30',
    close: '16:00',
    currency: 'HKD',
    color: '#d62828',
    symbols: ['0700.HK', '0005.HK', '0939.HK', '0388.HK', '1299.HK', '2318.HK'],
  },
  SSE: {
    id: 'SSE',
    name: 'Shanghai Stock Exchange',
    country: 'China',
    flag: '🇨🇳',
    timezone: 'Asia/Shanghai',
    open: '09:30',
    close: '15:00',
    currency: 'CNY',
    color: '#e63946',
    symbols: ['600036.SS', '601398.SS', '601288.SS', '600028.SS', '601857.SS'],
  },
  NIKKEI: {
    id: 'NIKKEI',
    name: 'Tokyo Stock Exchange',
    country: 'Japan',
    flag: '🇯🇵',
    timezone: 'Asia/Tokyo',
    open: '09:00',
    close: '15:30',
    currency: 'JPY',
    color: '#9b5de5',
    symbols: ['7203.T', '9984.T', '6758.T', '8306.T', '6501.T', '7267.T'],
  },
  EURONEXT: {
    id: 'EURONEXT',
    name: 'Euronext (Paris/Amsterdam)',
    country: 'Europe',
    flag: '🇪🇺',
    timezone: 'Europe/Paris',
    open: '09:00',
    close: '17:30',
    currency: 'EUR',
    color: '#0066cc',
    symbols: ['MC.PA', 'OR.PA', 'SAN.PA', 'AIR.PA', 'BNP.PA', 'TTE.PA'],
  },
  FRANKFURT: {
    id: 'FRANKFURT',
    name: 'Frankfurt Stock Exchange (XETRA)',
    country: 'Germany',
    flag: '🇩🇪',
    timezone: 'Europe/Berlin',
    open: '08:00',
    close: '22:00',
    currency: 'EUR',
    color: '#4a9fe8',
    symbols: ['SAP.DE', 'BMW.DE', 'VOW3.DE', 'SIE.DE', 'ALV.DE', 'BAS.DE'],
  },
  CRYPTO: {
    id: 'CRYPTO',
    name: 'Crypto Markets (24/7)',
    country: 'Global',
    flag: '🌐',
    timezone: 'UTC',
    open: '00:00',
    close: '23:59',
    currency: 'USD',
    color: '#f7931a',
    symbols: ['bitcoin', 'ethereum', 'binancecoin', 'solana', 'cardano', 'ripple', 'polkadot', 'dogecoin'],
  },
};

// Default watchlist for new users
export const DEFAULT_WATCHLIST = [
  { symbol: 'AAPL', exchange: 'NASDAQ', name: 'Apple Inc.' },
  { symbol: 'MSFT', exchange: 'NASDAQ', name: 'Microsoft Corp.' },
  { symbol: 'GOOGL', exchange: 'NASDAQ', name: 'Alphabet Inc.' },
  { symbol: 'NVDA', exchange: 'NASDAQ', name: 'NVIDIA Corp.' },
  { symbol: 'TSLA', exchange: 'NASDAQ', name: 'Tesla Inc.' },
  { symbol: 'JPM', exchange: 'NYSE', name: 'JPMorgan Chase' },
  { symbol: 'AMZN', exchange: 'NASDAQ', name: 'Amazon.com Inc.' },
  { symbol: 'META', exchange: 'NASDAQ', name: 'Meta Platforms' },
];

// Major market indices
export const MARKET_INDICES = [
  { symbol: '^GSPC', name: 'S&P 500', exchange: 'NYSE' },
  { symbol: '^IXIC', name: 'NASDAQ', exchange: 'NASDAQ' },
  { symbol: '^DJI', name: 'Dow Jones', exchange: 'NYSE' },
  { symbol: '^FTSE', name: 'FTSE 100', exchange: 'LSE' },
  { symbol: '^N225', name: 'Nikkei 225', exchange: 'NIKKEI' },
  { symbol: '^HSI', name: 'Hang Seng', exchange: 'HKEX' },
  { symbol: '^BSESN', name: 'SENSEX', exchange: 'BSE' },
  { symbol: '^NSEI', name: 'NIFTY 50', exchange: 'NSE' },
  { symbol: '^AXJO', name: 'ASX 200', exchange: 'ASX' },
  { symbol: '^STOXX50E', name: 'Euro Stoxx 50', exchange: 'EURONEXT' },
];

// HFT Simulation parameters
export const HFT_STRATEGIES = [
  { id: 'market_making', name: 'Market Making', description: 'Provide liquidity by placing both buy and sell orders' },
  { id: 'stat_arb', name: 'Statistical Arbitrage', description: 'Exploit price differences between correlated securities' },
  { id: 'momentum', name: 'Momentum Trading', description: 'Follow short-term price trends' },
  { id: 'mean_reversion', name: 'Mean Reversion', description: 'Bet price returns to historical average' },
  { id: 'latency_arb', name: 'Latency Arbitrage', description: 'Exploit speed advantages between venues' },
];

// News sources
export const NEWS_SOURCES = [
  { name: 'Reuters', url: 'https://www.reuters.com/business/finance/', logo: '📰' },
  { name: 'Bloomberg', url: 'https://www.bloomberg.com/markets', logo: '📊' },
  { name: 'Financial Times', url: 'https://www.ft.com/markets', logo: '🗞️' },
  { name: 'WSJ', url: 'https://www.wsj.com/news/markets', logo: '📃' },
  { name: 'CNBC', url: 'https://www.cnbc.com/markets/', logo: '📺' },
];

// Demo portfolio for new users
export const DEMO_PORTFOLIO = {
  balance: 100000,
  positions: [
    { symbol: 'AAPL', shares: 10, avgPrice: 170.50, currentPrice: 175.20 },
    { symbol: 'MSFT', shares: 5, avgPrice: 380.00, currentPrice: 395.50 },
    { symbol: 'NVDA', shares: 3, avgPrice: 850.00, currentPrice: 920.00 },
    { symbol: 'TSLA', shares: 8, avgPrice: 200.00, currentPrice: 215.00 },
  ],
};
